version: 2.1
orbs:
  node: circleci/node@4.0.0
  docker: circleci/docker@1.4.0
jobs:
  test:
    executor: node/default
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn run test
          name: Run YARN tests
workflows:
  pipline:
    jobs:
      - test
      - docker/publish:
          image: $CIRCLE_PROJECT_USERNAME/$CIRCLE_PROJECT_REPONAME
          requires:
            - test
